---
title: "Homework1"
author: Jyoti Kumar
output: github_document
---

This is my R Markdown File for Homework1

```{r}
library(tidyverse)
```


## Problem 1

## Creating a data frame

```{r create_df}
prob1_df =  
   tibble(
    samp = rnorm(10),
    samp_gt_0 = samp > 0,
    char_vec = c("a", "b", "c", "d", "e", "f", "g", "h", "i", "j"),
    factor_vec = factor(c("low","low","low","mod", "mod", "mod", "mod", "high", "high", "high")),
    )
```

 Taking the mean of each variable in the data frame.

```{r mean_pull_variables}
mean(pull(prob1_df,samp))
mean(pull(prob1_df, samp_gt_0))
mean(pull(prob1_df, char_vec))
mean(pull(prob1_df, factor_vec))
```

 We can take the mean of numbers and logical terms but not of characters and factors. 

```{r conversion_to_numeric}
as.numeric(pull(prob1_df,samp))
as.numeric(pull(prob1_df, samp_gt_0))
as.numeric(pull(prob1_df, char_vec))
as.numeric(pull(prob1_df, factor_vec))
```


```{r}
as.numeric(pull(prob1_df,samp_gt_0)) * pull(prob1_df,samp)
(pull(prob1_df, factor_vec)) * pull(prob1_df, samp)
as.numeric(pull(prob1_df, factor_vec)) * pull(prob1_df, samp)
```

 We can multiply numeric data with the random sample but not factors.


## Problem 2

